### ISSUE TITLE
Ajouter la possibilité de déposer les fichiers de trace directement sur l'interface web

### ISSUE THREAD

**Issue by WassimDhib** [leadwire-apm/flamescope#1]
pour créer des fichiers trace : voir  https://github.com/leadwire-apm/flamescope#installation--instructions

![image.png](https://zube.io/files/lead-wire/f9b513801006c3731986d1635f1a32d1-image.png)

**Comment by hameddhib** [comment]
Fixed

**Comment by leadwire-apm** [comment]
وحش
